# Konzeptionelle Überlegungen

Bevor wir ein Korpus zusammenstellen, müssen wir eine Vorstellung davon haben, was das Korpus beinhalten soll. Die Zusammenstellung des Korpus ergibt sich aus den Erfordernissen der jeweiligen Forschungsfrage – in Kombination mit möglichen Beschränkungen, die sich aus der Datenverfügbarkeit ergeben. So ist aus offensichtlichen Gründen ein Korpus zum Sprachgebrauch auf Wikipedia einfacher zusammenzustellen als ein hypothetisches Korpus zum Sprachgebrauch verdeckter Ermittler:innen in Usbekistan.

Im Folgenden wollen wir beispielhaft ein Korpus zusammenstellen, mit dem wir die Verwendung konzeptueller Metaphern im netzpolitischen Diskurs um die sog. Chatkontrolle. Dafür stützen wir uns auf Daten aus dem bereits erwähnten Portal netzpolitik.org. (Dass das Portal zur Chatkontrolle eine relativ klare, nämlich ablehnende, Position hat, stellt dabei für unsere Fragestellung, die ja auf die Untersuchung konzeptueller Metaphern abzielt, kein Problem dar, sondern kann durchaus auch ein Vorteil sein, da wir so auch die Frage stellen können, wie Metaphern zum "Framing" entsprechender politischer Pläne genutzt werden können. Gleichwohl wäre es für eine tatsächliche Analyse natürlich sinnvoll, sich bei der Erstellung eines Korpus auf mehr als nur ein Portal zu stützen.)

Die Datenmenge, die wir benötigen, hängt ebenfalls davon ab, was unsere Forschungsfrage ist und wie wir sie methodisch angehen wollen. Für eher quantitativ orientierte Herangehensweisen brauchen wir naturgemäß größere Datenmengen, für qualitative Arbeit genügt es oft, einige wenige Texte (diese aber vollständig und gründlich) einzubeziehen.

Auch wenn oft danach gefragt wird, ist es unmöglich, genaue Zahlen für die angemessene Größe eines Korpus zu nennen. Letztlich ist die Frage nach der Korpusgröße gerade für Seminar- und Abschlussarbeiten auch eher sekundär, solange die Analyse überzeugt.